data:
  source: "binance"
  pair: "BTC/USDT"
  timeframes:
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"
  since: "2022-01-01"
  limit: true
  cache: true
  cache_path: "data/cache/"